name: Froxlor-CI-MariaDB
on: [ 'push', 'pull_request', 'create' ]

jobs:
  nightly:
    name: Create nightly/testing tarball
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build
        working-directory: .

      - name: Setting file/directory permissionsr
        run: |
          find -exec chmod ugo+r,u+w,go-w {} \;
          find -type f -exec chmod ugo-x {} \;
          find -type d -exec chmod ugo+x {} \;
          chmod 0755 bin/froxlor-cli

      - name: Remove vcs and unneeded files
        run: |
          rm .gitignore
          rm .editorconfig
          rm -rf node_modules
          rm composer.json
          rm composer.lock
          rm package.json
          rm package-lock.json
          rm *.xml
          rm vite.config.js

      - name: Create empty index.html in built assets directory
        run: |
          touch templates/Froxlor/build/index.html
          touch templates/Froxlor/build/assets/index.html

      - name: Set nightly branding
        run: |
          sed -i "s/const BRANDING = '';/const BRANDING = '+nightly.${{github.event.after}}';/" lib/Froxlor/Froxlor.php
          zip -r froxlor-nightly.${{github.event.after}}.zip . -x "*.git*"
          sha256sum froxlor-nightly.${{github.event.after}}.zip > froxlor-nightly.${{github.event.after}}.zip.sha256
          mkdir dist
          mv froxlor-nightly.${{github.event.after}}.zip dist/
          mv froxlor-nightly.${{github.event.after}}.zip.sha256 dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: current-nightly
          path: |
            dist


#      - name: Deploy nightly to server
#        uses: easingthemes/ssh-deploy@v3.4.3
#        env:
#          ARGS: "-rltDzvO --chown=${{ secrets.WEB_USER }}:${{ secrets.WEB_USER }}"
#          SOURCE: "dist/"
#          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: "${{ secrets.REMOTE_TARGET }}/nightly/"
